/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
      },
      padding: {
        'safe': 'env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left)',
      },
      height: {
        'screen-safe': 'calc(100vh - env(safe-area-inset-top) - env(safe-area-inset-bottom))',
      },
      minHeight: {
        'screen-safe': 'calc(100vh - env(safe-area-inset-top) - env(safe-area-inset-bottom))',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-primary', 'text-primary-foreground', 'bg-card', 'text-card-foreground',
    'bg-secondary', 'text-secondary-foreground', 'bg-muted', 'text-muted-foreground',
    'bg-accent', 'text-accent-foreground', 'bg-destructive', 'text-destructive-foreground',
    'border', 'rounded-lg', 'rounded-md', 'rounded-sm', 'shadow-sm',
    'h-10', 'h-11', 'h-9', 'h-4', 'w-full', 'w-10', 'px-4', 'px-3', 'px-8', 'py-2', 'py-0.5',
    'inline-flex', 'items-center', 'justify-center', 'gap-2', 'font-medium', 'font-semibold',
    'transition-colors', 'focus-visible:outline-none', 'focus-visible:ring-2', 'focus-visible:ring-ring',
    'focus-visible:ring-offset-2', 'disabled:pointer-events-none', 'disabled:opacity-50',
    'text-xs', 'text-sm', 'text-2xl', 'leading-none', 'tracking-tight', 'space-y-1.5', 'p-6',
    'border-input', 'bg-background', 'hover:bg-accent', 'hover:text-accent-foreground',
    'hover:bg-primary/90', 'hover:bg-secondary/80', 'hover:bg-destructive/90', 'hover:bg-primary/80',
    'hover:bg-secondary/80', 'hover:bg-destructive/80', 'hover:underline', 'underline-offset-4',
    'bg-muted', 'text-muted-foreground', 'bg-popover', 'text-popover-foreground',
    'bg-card', 'text-card-foreground', 'bg-secondary', 'text-secondary-foreground',
    'bg-primary', 'text-primary-foreground', 'bg-accent', 'text-accent-foreground',
    'bg-destructive', 'text-destructive-foreground', 'bg-ring', 'text-ring',
    'bg-foreground', 'text-foreground', 'bg-background', 'text-background',
    'bg-popover', 'text-popover-foreground', 'bg-card', 'text-card-foreground',
    'bg-secondary', 'text-secondary-foreground', 'bg-primary', 'text-primary-foreground',
    'bg-accent', 'text-accent-foreground', 'bg-destructive', 'text-destructive-foreground',
    'bg-ring', 'text-ring', 'bg-foreground', 'text-foreground', 'bg-background', 'text-background',
    'rounded-full', 'border-transparent', 'border', 'border-input', 'border-red-800', 'border-gray-700',
    'border-gray-600', 'border-gray-800', 'border-gray-900', 'border-gray-500', 'border-gray-400',
    'border-gray-300', 'border-gray-200', 'border-gray-100', 'border-blue-600', 'border-green-600',
    'border-yellow-800', 'border-yellow-900', 'border-purple-600', 'border-indigo-600', 'border-teal-600',
    'border-emerald-600', 'border-orange-600', 'border-blue-900', 'border-green-900', 'border-red-900',
    'border-purple-900', 'border-indigo-900', 'border-teal-900', 'border-emerald-900', 'border-orange-900',
    'bg-blue-600', 'bg-green-600', 'bg-yellow-800', 'bg-yellow-900', 'bg-purple-600', 'bg-indigo-600',
    'bg-teal-600', 'bg-emerald-600', 'bg-orange-600', 'bg-blue-900', 'bg-green-900', 'bg-red-900',
    'bg-purple-900', 'bg-indigo-900', 'bg-teal-900', 'bg-emerald-900', 'bg-orange-900',
    'text-blue-600', 'text-green-600', 'text-yellow-800', 'text-yellow-900', 'text-purple-600',
    'text-indigo-600', 'text-teal-600', 'text-emerald-600', 'text-orange-600', 'text-blue-900',
    'text-green-900', 'text-red-900', 'text-purple-900', 'text-indigo-900', 'text-teal-900',
    'text-emerald-900', 'text-orange-900', 'text-white', 'text-black', 'text-gray-300', 'text-gray-400',
    'text-gray-500', 'text-gray-600', 'text-gray-700', 'text-gray-800', 'text-gray-900',
    'bg-white', 'bg-black', 'bg-gray-300', 'bg-gray-400', 'bg-gray-500', 'bg-gray-600', 'bg-gray-700',
    'bg-gray-800', 'bg-gray-900', 'shadow', 'shadow-sm', 'shadow-md', 'shadow-lg', 'shadow-xl',
    'p-3', 'p-4', 'p-6', 'pb-2', 'pb-20', 'mb-2', 'mb-4', 'mt-1', 'mt-2', 'mt-4', 'mt-8',
    'flex', 'flex-col', 'flex-row', 'items-center', 'justify-center', 'justify-between', 'gap-2',
    'max-w-max', 'w-full', 'h-full', 'overflow-hidden', 'overflow-x-auto', 'overflow-y-auto',
    'rounded', 'rounded-lg', 'rounded-md', 'rounded-sm', 'rounded-full', 'rounded-t-lg', 'rounded-b-lg',
    'rounded-t-md', 'rounded-b-md', 'rounded-t-sm', 'rounded-b-sm', 'rounded-t-full', 'rounded-b-full',
    'z-10', 'z-20', 'z-30', 'z-40', 'z-50', 'z-9999', 'relative', 'absolute', 'fixed', 'top-0', 'left-0',
    'right-0', 'bottom-0', 'inset-0', 'space-y-2', 'space-y-4', 'space-x-2', 'space-x-4', 'grid',
    'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4', 'gap-4', 'gap-2', 'gap-1', 'col-span-1',
    'col-span-2', 'col-span-3', 'col-span-4', 'row-span-1', 'row-span-2', 'row-span-3', 'row-span-4',
    'text-center', 'text-left', 'text-right', 'font-bold', 'font-medium', 'font-semibold', 'font-light',
    'font-normal', 'font-thin', 'uppercase', 'lowercase', 'capitalize', 'tracking-wide', 'tracking-tight',
    'leading-none', 'leading-tight', 'leading-snug', 'leading-normal', 'leading-relaxed', 'leading-loose',
    'transition', 'transition-all', 'transition-colors', 'duration-100', 'duration-200', 'duration-300',
    'duration-500', 'duration-700', 'duration-1000', 'ease-in', 'ease-out', 'ease-in-out',
    'bg-gradient-to-b', 'bg-gradient-to-t', 'bg-gradient-to-l', 'bg-gradient-to-r',
    'from-primary', 'to-primary', 'from-secondary', 'to-secondary', 'from-accent', 'to-accent',
    'from-destructive', 'to-destructive', 'from-muted', 'to-muted', 'from-card', 'to-card',
    'from-background', 'to-background', 'from-foreground', 'to-foreground',
    'bg-opacity-50', 'bg-opacity-75', 'bg-opacity-90', 'bg-opacity-100',
    'opacity-0', 'opacity-25', 'opacity-50', 'opacity-75', 'opacity-100',
    'pointer-events-none', 'pointer-events-auto', 'select-none', 'select-auto',
    'cursor-pointer', 'cursor-default', 'cursor-not-allowed',
    'w-4', 'h-4', 'w-6', 'h-6', 'w-8', 'h-8', 'w-12', 'h-12', 'w-16', 'h-16',
    'w-24', 'h-24', 'w-32', 'h-32', 'w-48', 'h-48', 'w-64', 'h-64', 'w-80', 'h-80',
    'w-96', 'h-96', 'w-screen', 'h-screen', 'min-h-screen', 'max-h-screen',
    'min-w-screen', 'max-w-screen', 'overflow-x-hidden', 'overflow-y-hidden',
    'overflow-x-auto', 'overflow-y-auto', 'overflow-hidden',
    'bg-[#0B0E1F]', 'bg-[#121212]', 'bg-[#1a1a2e]', 'bg-[#000000]'
  ],
}